package com.xaduin.invoduin.persistence.domain;
// Generated Apr 21, 2015 7:11:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Companies generated by hbm2java
 */
public class Companies  implements java.io.Serializable {


     private Integer idcompanies;
     private boolean available;
     private String cif;
     private String nameCommercial;
     private String name;
     private String address;
     private Integer cp;
     private String city;
     private String state;
     private String country;
     private String tlf;
     private Set invoiceses = new HashSet(0);
     private Set pickingses = new HashSet(0);

    public Companies() {
    }

	
    public Companies(boolean available) {
        this.available = available;
    }
    public Companies(boolean available, String cif, String nameCommercial, String name, String address, Integer cp, String city, String state, String country, String tlf, Set invoiceses, Set pickingses) {
       this.available = available;
       this.cif = cif;
       this.nameCommercial = nameCommercial;
       this.name = name;
       this.address = address;
       this.cp = cp;
       this.city = city;
       this.state = state;
       this.country = country;
       this.tlf = tlf;
       this.invoiceses = invoiceses;
       this.pickingses = pickingses;
    }
   
    public Integer getIdcompanies() {
        return this.idcompanies;
    }
    
    public void setIdcompanies(Integer idcompanies) {
        this.idcompanies = idcompanies;
    }
    public boolean isAvailable() {
        return this.available;
    }
    
    public void setAvailable(boolean available) {
        this.available = available;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getNameCommercial() {
        return this.nameCommercial;
    }
    
    public void setNameCommercial(String nameCommercial) {
        this.nameCommercial = nameCommercial;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }
    public Set getInvoiceses() {
        return this.invoiceses;
    }
    
    public void setInvoiceses(Set invoiceses) {
        this.invoiceses = invoiceses;
    }
    public Set getPickingses() {
        return this.pickingses;
    }
    
    public void setPickingses(Set pickingses) {
        this.pickingses = pickingses;
    }




}


