package com.xaduin.invoduin.persistence.domain;
// Generated Apr 21, 2015 7:11:40 PM by Hibernate Tools 4.3.1



/**
 * Picklines generated by hbm2java
 */
public class Picklines  implements java.io.Serializable {


     private Integer idpicklines;
     private Pickings pickings;
     private Products products;
     private Double amount;
     private Double price;
     private Double taxamount;

    public Picklines() {
    }

	
    public Picklines(Pickings pickings, Products products) {
        this.pickings = pickings;
        this.products = products;
    }
    public Picklines(Pickings pickings, Products products, Double amount, Double price, Double taxamount) {
       this.pickings = pickings;
       this.products = products;
       this.amount = amount;
       this.price = price;
       this.taxamount = taxamount;
    }
   
    public Integer getIdpicklines() {
        return this.idpicklines;
    }
    
    public void setIdpicklines(Integer idpicklines) {
        this.idpicklines = idpicklines;
    }
    public Pickings getPickings() {
        return this.pickings;
    }
    
    public void setPickings(Pickings pickings) {
        this.pickings = pickings;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getTaxamount() {
        return this.taxamount;
    }
    
    public void setTaxamount(Double taxamount) {
        this.taxamount = taxamount;
    }




}


