package com.xaduin.invoduin.persistence.domain;
// Generated Apr 21, 2015 7:11:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pickings generated by hbm2java
 */
public class Pickings  implements java.io.Serializable {


     private Integer idpickings;
     private Companies companies;
     private Invoices invoices;
     private String number;
     private Date date;
     private Boolean committed;
     private boolean invoiced;
     private Set picklineses = new HashSet(0);

    public Pickings() {
    }

	
    public Pickings(Companies companies, Invoices invoices, String number, Date date, boolean invoiced) {
        this.companies = companies;
        this.invoices = invoices;
        this.number = number;
        this.date = date;
        this.invoiced = invoiced;
    }
    public Pickings(Companies companies, Invoices invoices, String number, Date date, Boolean committed, boolean invoiced, Set picklineses) {
       this.companies = companies;
       this.invoices = invoices;
       this.number = number;
       this.date = date;
       this.committed = committed;
       this.invoiced = invoiced;
       this.picklineses = picklineses;
    }
   
    public Integer getIdpickings() {
        return this.idpickings;
    }
    
    public void setIdpickings(Integer idpickings) {
        this.idpickings = idpickings;
    }
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }
    public Invoices getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Invoices invoices) {
        this.invoices = invoices;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Boolean getCommitted() {
        return this.committed;
    }
    
    public void setCommitted(Boolean committed) {
        this.committed = committed;
    }
    public boolean isInvoiced() {
        return this.invoiced;
    }
    
    public void setInvoiced(boolean invoiced) {
        this.invoiced = invoiced;
    }
    public Set getPicklineses() {
        return this.picklineses;
    }
    
    public void setPicklineses(Set picklineses) {
        this.picklineses = picklineses;
    }




}


