package com.xaduin.invoduin.persistence.domain;
// Generated Apr 21, 2015 7:11:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer idProduct;
     private String title;
     private String type;
     private String units;
     private double price;
     private String description;
     private Set picklineses = new HashSet(0);

    public Products() {
    }

	
    public Products(String title, String type, String units, double price, String description) {
        this.title = title;
        this.type = type;
        this.units = units;
        this.price = price;
        this.description = description;
    }
    public Products(String title, String type, String units, double price, String description, Set picklineses) {
       this.title = title;
       this.type = type;
       this.units = units;
       this.price = price;
       this.description = description;
       this.picklineses = picklineses;
    }
   
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getUnits() {
        return this.units;
    }
    
    public void setUnits(String units) {
        this.units = units;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getPicklineses() {
        return this.picklineses;
    }
    
    public void setPicklineses(Set picklineses) {
        this.picklineses = picklineses;
    }




}


