package com.xaduin.invoduin.persistence.domain;
// Generated Apr 21, 2015 7:11:40 PM by Hibernate Tools 4.3.1



/**
 * TaxsClient generated by hbm2java
 */
public class TaxsClient  implements java.io.Serializable {


     private Integer idtaxs;
     private String title;
     private String description;
     private Double percentage;

    public TaxsClient() {
    }

    public TaxsClient(String title, String description, Double percentage) {
       this.title = title;
       this.description = description;
       this.percentage = percentage;
    }
   
    public Integer getIdtaxs() {
        return this.idtaxs;
    }
    
    public void setIdtaxs(Integer idtaxs) {
        this.idtaxs = idtaxs;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(Double percentage) {
        this.percentage = percentage;
    }




}


